# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/catalogs', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Catalog. As you add validations to Catalog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Catalog.create! valid_attributes
      get catalogs_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      catalog = Catalog.create! valid_attributes
      get catalog_url(catalog)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_catalog_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      catalog = Catalog.create! valid_attributes
      get edit_catalog_url(catalog)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Catalog' do
        expect do
          post catalogs_url, params: { catalog: valid_attributes }
        end.to change(Catalog, :count).by(1)
      end

      it 'redirects to the created catalog' do
        post catalogs_url, params: { catalog: valid_attributes }
        expect(response).to redirect_to(catalog_url(Catalog.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Catalog' do
        expect do
          post catalogs_url, params: { catalog: invalid_attributes }
        end.to change(Catalog, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post catalogs_url, params: { catalog: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested catalog' do
        catalog = Catalog.create! valid_attributes
        patch catalog_url(catalog), params: { catalog: new_attributes }
        catalog.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the catalog' do
        catalog = Catalog.create! valid_attributes
        patch catalog_url(catalog), params: { catalog: new_attributes }
        catalog.reload
        expect(response).to redirect_to(catalog_url(catalog))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        catalog = Catalog.create! valid_attributes
        patch catalog_url(catalog), params: { catalog: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested catalog' do
      catalog = Catalog.create! valid_attributes
      expect do
        delete catalog_url(catalog)
      end.to change(Catalog, :count).by(-1)
    end

    it 'redirects to the catalogs list' do
      catalog = Catalog.create! valid_attributes
      delete catalog_url(catalog)
      expect(response).to redirect_to(catalogs_url)
    end
  end
end
